const {
  REACT_APP_API_URL,
  REACT_APP_USER_COOKIE,
  REACT_APP_VALIDATION_COOKIE,
  REACT_APP_RECOVERING_COOKIE,
  REACT_APP_USER_NATION,
  REACT_APP_USER_NICK,
} = process.env;

const config = {
  apiUrl: REACT_APP_API_URL,
  userNick: REACT_APP_USER_NICK,
  userCookie: REACT_APP_USER_COOKIE,
  userNation: REACT_APP_USER_NATION,
  validationCookie: REACT_APP_VALIDATION_COOKIE,
  recoveringCookie: REACT_APP_RECOVERING_COOKIE,
};

export default config;
